name: mapcon-ct

services:
  postgres:
    container_name: postgresql
    image: postgres:16.6
    environment:
      POSTGRES_DB: mapcon
      POSTGRES_USER: mapcon
      POSTGRES_PASSWORD: mapcon
    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - "~/docker/volumes/keycloak/postgresql:/var/lib/postgresql"
      - "~/docker/volumes/keycloak/postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"

  mapcon:
    container_name: deaau-mapcon
    image: "${COMPOSE_PROJECT_NAME}:node-${NODE_VERSION}"
    build:
      context: .
      args:
        PLATFORM: ${PLATFORM}
        PROJECT: ${COMPOSE_PROJECT_NAME}
        NODE_VERSION: ${NODE_VERSION}
    ports:
      - "8080:8080"
    env_file:
      - path: env/${COMPOSE_PROJECT_NAME}.env
        required: true
    depends_on:
      postgres:
        condition: service_healthy
